"""Initial migration with utilisateur and post

Revision ID: 35d4a8329283
Revises: 
Create Date: 2025-09-26 12:49:06.282021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d4a8329283'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_utilisateur', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mot_passe_hash', sa.String(length=256), nullable=True),
    sa.Column('a_propos_moi', sa.String(length=140), nullable=True),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utilisateur_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_utilisateur_nom_utilisateur'), ['nom_utilisateur'], unique=True)

    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utilisateur_nom_utilisateur'))
        batch_op.drop_index(batch_op.f('ix_utilisateur_email'))

    op.drop_table('utilisateur')
    # ### end Alembic commands ###
